import type { WrappedYear } from "@/types";

export const wrappedYears: WrappedYear[] = [
  {
    year: 2026,
    gradient: "linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)",
    headline: "SWE Intern @ Capital One | Co-Founder @ MadLease",
    stat: "You started thinking long-term",
    company: "Capital One / MadLease",
    role: "Software Engineer Intern",
    color: "#4facfe",
    icon: "/icons/rocket.svg",
    points: [
      "Joined Capital One as a Software Engineer Intern — architected a graph-RAG pipeline that translates plain-English requirements into validated fulfillment workflow configs, cutting build time from 2+ days to under an hour for intent engineers",
      "Scaled MadLease to 200+ accounts, 90+ listings, and 5+ building partners as co-founder and full-stack owner of the technical stack",
      "Eliminated backend image traffic for 1000+ uploads by architecting browser-direct S3 transfers with presigned PUT URLs, CloudFront CDN delivery, and Firebase UID/IP token-bucket rate limiting",
      "Boosted listing visibility across 25+ crawler types by serving structured metadata through Vercel Edge Middleware while routing real users straight to the React SPA",
    ],
  },
  {
    year: 2025,
    gradient: "linear-gradient(135deg, #00b894 0%, #00cec9 100%)",
    headline: "Full-Stack SWE Intern @ Entegral | RAG Engineer @ Denari | Founder @ MadLease",
    stat: "You scaled production systems",
    company: "Entegral / Denari / MadLease",
    role: "Full Stack Software Engineer Intern",
    color: "#00b894",
    icon: "/icons/rocket.svg",
    points: [
      "Led development of a production-ready crash photo capture and insurance intake platform at Entegral, shipping a company-wide reusable OCR module that extracted VIN, license plate, and odometer fields with 90%+ accuracy",
      "Eliminated polling for estimate negotiation data by building a Pub/Sub database listener that propagated updates across multiple internal services in real time",
      "Built a citation-grounded RAG pipeline for Denari that outperformed GPT-4o-mini by 5% across 2,200+ CPA benchmark questions using OpenAI embeddings, TimescaleDB/pgvector, and AWS S3",
      "Founded and deployed MadLease — a UW–Madison sublease marketplace — and designed a ranking engine matching listings to users across 7 filter dimensions including price, location, amenities, and date availability",
      "Accepted Capital One's TIP Software Engineer offer for Summer 2026",
    ],
  },
  {
    year: 2024,
    gradient: "linear-gradient(135deg, #a29bfe 0%, #6c5ce7 100%)",
    headline: "Machine Learning Engineer @ Astro AI Trading",
    stat: "You started taking ownership",
    company: "Astro AI Trading / UW-Madison",
    role: "Machine Learning Engineer",
    color: "#a29bfe",
    icon: "/icons/ml.svg",
    points: [
      "Promoted to Machine Learning Engineer at Astro AI Trading — led a 3-engineer team building sector-specific stock forecasting models that fused market data with sentiment from 60+ daily news and social media sources, improving prediction accuracy by 32%",
      "Built a BERT + PCA + KMeans article routing pipeline that classified financial news with 77% accuracy, sharpening sentiment signal quality for sector-specific forecasting models",
      "Built the first version of QuizClash at a hackathon — a real-time Kahoot-style platform that turns uploaded PDFs and YouTube videos into playable quiz games",
      "Scaled QuizClash to 40+ concurrent players with a WebSocket engine and a 5-stage ML pipeline (OCR, Whisper, T5, RoBERTa, Sense2Vec) for question generation",
    ],
  },
  {
    year: 2023,
    gradient: "linear-gradient(135deg, #ff9f43 0%, #ee5a24 100%)",
    headline: "Data Science Intern @ Astro AI Trading",
    stat: "You started shipping real systems",
    company: "University of Wisconsin-Madison",
    role: "Computer Science & Data Science Student",
    color: "#ff9f43",
    icon: "/icons/university.svg",
    points: [
      "Started Computer Science and Data Science at UW–Madison",
      "Built and deployed FlixFinder — my first full-stack app — using Django, PostgreSQL, Scikit-Learn, and React",
      "Joined Astro AI Trading as a Data Science Intern and implemented preprocessing pipelines for live trading sentiment models",
    ],
  },
];
