import type { WrappedYear } from "@/types";

export const wrappedYears: WrappedYear[] = [
  {
    year: 2026,
    gradient: "linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)",
    headline: "SWE Intern @ Capital One | TRAIL Lab Researcher | Co-Founder @ MadLease",
    stat: "You started thinking long-term",
    company: "Capital One / TRAIL Lab / MadLease",
    role: "Software Engineer Intern",
    color: "#4facfe",
    points: [
      "Joined Capital One as a Software Engineer Intern — designed a GraphRAG pipeline that translates plain-English requirements into validated card fulfillment workflow configs, reaching 100% structural validity and 88% required-field completeness across 70 test configs and cutting build time from 2+ days to under an hour",
      "Built real-time graph validation (cycle detection, unreachable-state and invalid-reference checks) into a React/Monaco editor, adopted by 20+ intent engineers",
      "Joined UW–Madison's TRAIL research lab as an undergraduate research assistant, designing the tool-integration layer for an MCP-compatible multi-agent Q&A system with cross-tool retrieval and access controls, and red-teaming it against prompt injection and unauthorized tool use",
      "Scaled MadLease to 250+ accounts, 100+ listings, and 5+ building partners as co-founder and full-stack owner of the technical stack",
      "Moved image uploads to browser-direct S3 via presigned PUT URLs with retry/rollback handling across 1,000+ uploads, backed by CloudFront CDN delivery and Firebase UID/IP token-bucket rate limiting",
      "Boosted listing visibility across 25+ crawler types by serving structured metadata through Vercel Edge Middleware while routing real users straight to the React SPA",
    ],
  },
  {
    year: 2025,
    gradient: "linear-gradient(135deg, #00b894 0%, #00cec9 100%)",
    headline: "Full-Stack SWE Intern @ Entegral | RAG Engineer @ Denari | Co-Founder @ MadLease",
    stat: "You scaled production systems",
    company: "Entegral / Denari / MadLease",
    role: "Full Stack Software Engineer Intern",
    color: "#00b894",
    points: [
      "Led development of a production-ready crash photo capture and insurance intake platform at Entegral, replacing hard-coded crash-intake logic with configurable per-workflow documentation rules so providers could define claim requirements without code changes",
      "Shipped a company-wide reusable OCR module (Angular + Tesseract.js) that re-read VIN, license plate, and odometer fields in a background worker until each passed validation, reaching 90%+ accuracy",
      "Eliminated polling for estimate negotiation data by building a Pub/Sub database listener that propagated updates across multiple internal services in real time",
      "Built a citation-grounded tax RAG system for Denari indexing 50,000+ documents — answered 2,200+ CPA exam questions in ~30 minutes at 61% accuracy (outperforming GPT-4o-mini by 5 points and 10% on overall score), improving 14% in accuracy and 10% in citation quality over our first benchmark, all for under $5 in total compute cost",
      "Co-founded and deployed MadLease — a UW–Madison sublease marketplace — and fixed an IDOR vulnerability in the messaging service by adding conversation-membership authorization checks before allowing message reads",
      "Accepted Capital One's TIP Software Engineer offer for Summer 2026",
    ],
  },
  {
    year: 2024,
    gradient: "linear-gradient(135deg, #a29bfe 0%, #6c5ce7 100%)",
    headline: "Machine Learning Engineer @ Astro AI Trading",
    stat: "You started taking ownership",
    company: "Astro AI Trading / UW-Madison",
    role: "Machine Learning Engineer",
    color: "#a29bfe",
    points: [
      "Promoted to Machine Learning Engineer at Astro AI Trading — led a 3-engineer team building sector-specific stock forecasting models that fused technical, macroeconomic, and sentiment features from 60+ daily news and social media sources, cutting held-out RMSE by 16% vs. a price-only baseline",
      "Fine-tuned a BERT 3-class news-sentiment classifier reaching 77% test accuracy, and built a separate BERT + PCA + KMeans clustering pipeline to route each article to its relevant market sector before scoring",
      "Built the first version of QuizClash at a hackathon — a real-time Kahoot-style platform that turns uploaded PDFs and YouTube videos into playable quiz games",
      "Scaled QuizClash to 40+ concurrent players with a WebSocket engine and a 5-stage ML pipeline (OCR, Whisper, T5, RoBERTa, Sense2Vec) for question generation",
    ],
  },
  {
    year: 2023,
    gradient: "linear-gradient(135deg, #ff9f43 0%, #ee5a24 100%)",
    headline: "Data Science Intern @ Astro AI Trading",
    stat: "You started shipping real systems",
    company: "University of Wisconsin-Madison",
    role: "Computer Science & Data Science Student",
    color: "#ff9f43",
    points: [
      "Started Computer Science and Data Science at UW–Madison",
      "Built and deployed FlixFinder — my first full-stack app — using Django, PostgreSQL, Scikit-Learn, and React",
      "Joined Astro AI Trading as a Data Science Intern and implemented preprocessing pipelines for live trading sentiment models",
    ],
  },
];
